name: Audit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  audit:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Verify dependencies
      run: go mod verify

    - name: Get dependencies
      run: go mod download

    - name: Build
      run: go build -v

    - name: Run tests
      run: go test ./test/*.go